<a href="https://colab.research.google.com/github/SmirnovKol/8cc/blob/master/28_Dilated_Convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np,sys
from  scipy.signal import convolve2d

In [2]:
np.random.seed(678)
#tf.set_random_seed(6789)
#sess = tf.Session()

In [3]:
# ========== Experiment Set Up ===========
# 0. Create a matrix we want to perform experiments
mat_size = 10
matrix = np.zeros((mat_size,mat_size)).astype(np.float32) 

for x in range(4,7):
    for y in range(3,6):
        matrix[y,x] = 1

In [4]:
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [5]:
# 1. Create a Kernel 
kernel = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]).astype(np.float32) 
print("====== Original Set Up ======")
print("Matrix Shape : ",matrix.shape)
print(matrix)
print("kernel Shape : ",kernel.shape)
print(kernel)

====== Original Set Up ======
Matrix Shape :  (10, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
kernel Shape :  (3, 3)
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [6]:

# ========== Experiment Set Up ===========

# ========== EXAMPLE 1 - Dilation Factor 1 ===========
print("\n====== Dilated Kernel 1 ======")
print('Kernal For "Familiar" Convolution for Numpy: \n',kernel)

print("========== Numpy 'familiar' Convolution Results ===============")
np_results = convolve2d(matrix,kernel,mode='valid')
print("Numpy Results Shape: ",np_results.shape)
print(np_results)


====== Dilated Kernel 1 ======
Kernal For "Familiar" Convolution for Numpy: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
========== Numpy 'familiar' Convolution Results ===============
Numpy Results Shape:  (8, 8)
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  3.  6.  5.  3.  0.]
 [ 0.  0.  5. 12. 21. 16.  9.  0.]
 [ 0.  0. 12. 27. 45. 33. 18.  0.]
 [ 0.  0. 11. 24. 39. 28. 15.  0.]
 [ 0.  0.  7. 15. 24. 17.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [7]:
np.newaxis

In [8]:
None

In [9]:
np.newaxis is None

True

In [10]:
print("========== Tensorfow Conv2D Results ===============")
tf_result_1_1 = tf.nn.conv2d(np.expand_dims(np.expand_dims(matrix,axis=0),axis=3),
                            np.expand_dims(np.expand_dims(np.rot90(kernel,2),axis=2),axis=3),
                            strides=[1,1,1,1],padding="VALID",
                            dilations=[1,1,1,1])

========== Tensorfow Conv2D Results ===============


In [11]:
np.expand_dims(np.expand_dims(matrix,axis=0),axis=3).shape

(1, 10, 10, 1)

In [12]:
np.expand_dims(np.expand_dims(np.rot90(kernel,2),axis=2),axis=3).shape

(3, 3, 1, 1)

In [13]:
kernel

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [14]:
np.rot90(kernel, 1)

array([[3., 6., 9.],
       [2., 5., 8.],
       [1., 4., 7.]], dtype=float32)

In [15]:
np.rot90(kernel,2)

array([[9., 8., 7.],
       [6., 5., 4.],
       [3., 2., 1.]], dtype=float32)

In [16]:
m = np.arange(24).reshape((2,3,4))
m


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
np.rot90(m, 1, (0,2))

array([[[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 0, 12],
        [ 4, 16],
        [ 8, 20]]])

In [18]:
tf_result_1_1.shape

TensorShape([1, 8, 8, 1])

In [19]:
np.all([20, 0,  3], axis=0)

False

In [20]:
a111 = np.arange(24).reshape((2, 3, 4))

In [21]:
a111[1][1][2] = 0

In [22]:
a111

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17,  0, 19],
        [20, 21, 22, 23]]])

In [23]:
np.all(a111, axis=2, keepdims=True)

array([[[False],
        [ True],
        [ True]],

       [[ True],
        [False],
        [ True]]])

In [24]:
np.all([
  [0, 2, 3, 7],
  [23, 5, 0, 11]
], axis=0)

array([False,  True, False,  True])

In [25]:
np.all(np.squeeze(tf_result_1_1) == np_results)

True

In [26]:
"""
tf_result = sess.run(tf_opreation1_1)
print("Tensorfow Conv2D Results Shape: ",tf_result.shape)
print(np.squeeze(tf_result))
"""
# print("========== Tensorfow Atrous Conv2D Results ===============")
# tf_opreation1_2 = tf.nn.atrous_conv2d(np.expand_dims(np.expand_dims(matrix,axis=0),axis=3),
#                                     np.expand_dims(np.expand_dims(np.rot90(kernel,2),axis=3),axis=4),
#                                     rate=1,padding="VALID")
# tf_result = sess.run(tf_opreation1_2)
# print("Tensorfow Atrous Results Shape: ",tf_result.shape)
# print(np.squeeze(tf_result))
# ========== EXAMPLE 1 - Dilation Factor 1 ===========




# ========== EXAMPLE 2 - Dilation Factor 2 ===========
print("\n====== Dilated Kernel 2 ======")
kernel2 = np.array([
    [1,0,2,0,3],
    [0,0,0,0,0],
    [4,0,5,0,6],
    [0,0,0,0,0],
    [7,0,8,0,9]
])
print('Kernal For "Familiar" Convolution for Numpy: \n',kernel2)

print("========== Numpy 'familiar' Convolution Results ===============")
np_results = convolve2d(matrix,kernel2,mode='valid')
print("Numpy Results Shape: ",np_results.shape)
print(np_results)


====== Dilated Kernel 2 ======
Kernal For "Familiar" Convolution for Numpy: 
 [[1 0 2 0 3]
 [0 0 0 0 0]
 [4 0 5 0 6]
 [0 0 0 0 0]
 [7 0 8 0 9]]
========== Numpy 'familiar' Convolution Results ===============
Numpy Results Shape:  (6, 6)
[[ 1.  1.  3.  2.  5.  3.]
 [ 5.  5. 12.  7. 16.  9.]
 [ 4.  4.  9.  5. 11.  6.]
 [11. 11. 24. 13. 28. 15.]
 [ 7.  7. 15.  8. 17.  9.]
 [ 7.  7. 15.  8. 17.  9.]]


In [27]:


# print("========== Tensorfow Conv2D Results ===============")
# # tf_opreation2_1 = tf.nn.conv2d(np.expand_dims(np.expand_dims(matrix,axis=0),axis=3),
# #                             np.expand_dims(np.expand_dims(np.rot90(kernel,2),axis=3),axis=4),
# #                             strides=[1,1,1,1],padding="VALID",
# #                             dilations=[1,2,2,1])
# # tf_result = sess.run(tf_opreation2_1)
# # print("Tensorfow Conv2D Results Shape: ",tf_result.shape)
# # print(np.squeeze(tf_result))

print("========== Tensorfow Atrous Conv2D Results ===============")
tf_result = tf.nn.atrous_conv2d(np.expand_dims(np.expand_dims(matrix,axis=0),axis=3),
                                    np.expand_dims(np.expand_dims(np.rot90(kernel,2),axis=2),axis=3),
                                    rate=2,padding="VALID")
print("Tensorfow Atrous Results Shape: ",tf_result.shape)
print(np.squeeze(tf_result))
# ========== EXAMPLE 2 - Dilation Factor 2 ===========

========== Tensorfow Atrous Conv2D Results ===============
Tensorfow Atrous Results Shape:  (1, 6, 6, 1)
[[ 1.  1.  3.  2.  5.  3.]
 [ 5.  5. 12.  7. 16.  9.]
 [ 4.  4.  9.  5. 11.  6.]
 [11. 11. 24. 13. 28. 15.]
 [ 7.  7. 15.  8. 17.  9.]
 [ 7.  7. 15.  8. 17.  9.]]


In [28]:


# ========== EXAMPLE 3 - Dilation Factor 3 ===========
print("\n====== Dilated Kernel 3 ======")
kernel2 = np.array([
    [1,0,0,2,0,0,3],
    [0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0],
    [4,0,0,5,0,0,6],
    [0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0],
    [7,0,0,8,0,0,9]
])
print('Kernal For "Familiar" Convolution for Numpy: \n',kernel2)

print("========== Numpy 'familiar' Convolution Results ===============")
np_results = convolve2d(matrix,kernel2,mode='valid')
print("Numpy Results Shape: ",np_results.shape)
print(np_results)

print("========== Tensorfow Conv2D Results ===============")
tf_opreation4_1 = tf.nn.conv2d(np.expand_dims(np.expand_dims(matrix,axis=0),axis=3),
                            np.expand_dims(np.expand_dims(np.rot90(kernel,2),axis=2),axis=3),
                            strides=[1,1,1,1],padding="VALID",
                            dilations=[1,3,3,1])
# tf_result = sess.run(tf_opreation4_1)
print("Tensorfow Conv2D Results Shape: ",tf_opreation4_1.shape)
print(np.squeeze(tf_opreation4_1))

print("========== Tensorfow Atrous Conv2D Results ===============")
tf_opreation4_2 = tf.nn.atrous_conv2d(np.expand_dims(np.expand_dims(matrix,axis=0),axis=3),
                                    np.expand_dims(np.expand_dims(np.rot90(kernel,2),axis=2),axis=3),
                                    rate=3,padding="VALID")
print("Tensorfow Atrous Results Shape: ",tf_opreation4_2.shape)
print(np.squeeze(tf_opreation4_2))
# ========== EXAMPLE 3 - Dilation Factor 3 ===========


====== Dilated Kernel 3 ======
Kernal For "Familiar" Convolution for Numpy: 
 [[1 0 0 2 0 0 3]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [4 0 0 5 0 0 6]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [7 0 0 8 0 0 9]]
========== Numpy 'familiar' Convolution Results ===============
Numpy Results Shape:  (4, 4)
[[4. 5. 5. 5.]
 [4. 5. 5. 5.]
 [4. 5. 5. 5.]
 [7. 8. 8. 8.]]
========== Tensorfow Conv2D Results ===============
Tensorfow Conv2D Results Shape:  (1, 4, 4, 1)
[[4. 5. 5. 5.]
 [4. 5. 5. 5.]
 [4. 5. 5. 5.]
 [7. 8. 8. 8.]]
========== Tensorfow Atrous Conv2D Results ===============
Tensorfow Atrous Results Shape:  (1, 4, 4, 1)
[[4. 5. 5. 5.]
 [4. 5. 5. 5.]
 [4. 5. 5. 5.]
 [7. 8. 8. 8.]]


In [29]:

# ========== EXAMPLE 4 - Dilation Factor 4 ===========
print("\n====== Dilated Kernel 3 ======")
kernel2 = np.array([
    [1,0,0,0,2,0,0,0,3],
    [0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0],
    [4,0,0,0,5,0,0,0,6],
    [0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0],
    [7,0,0,0,8,0,0,0,9]
])
print('Kernal For "Familiar" Convolution for Numpy: \n',kernel2)

print("========== Numpy 'familiar' Convolution Results ===============")
np_results = convolve2d(matrix,kernel2,mode='valid')
print("Numpy Results Shape: ",np_results.shape)
print(np_results)

print("========== Tensorfow Conv2D Results ===============")
tf_opreation4_1 = tf.nn.conv2d(np.expand_dims(np.expand_dims(matrix,axis=0),axis=3),
                            np.expand_dims(np.expand_dims(np.rot90(kernel,2),axis=2),axis=3),
                            strides=[1,1,1,1],padding="VALID",
                            dilations=[1,4,4,1])
# tf_result = sess.run(tf_opreation4_1)
print("Tensorfow Conv2D Results Shape: ",tf_opreation4_1.shape)
print(np.squeeze(tf_opreation4_1))

print("========== Tensorfow Atrous Conv2D Results ===============")
tf_opreation4_2 = tf.nn.atrous_conv2d(np.expand_dims(np.expand_dims(matrix,axis=0),axis=3),
                                    np.expand_dims(np.expand_dims(np.rot90(kernel,2),axis=2),axis=3),
                                    rate=4,padding="VALID")
# tf_result = sess.run(tf_opreation4_2)
print("Tensorfow Atrous Results Shape: ",tf_opreation4_2.shape)
print(np.squeeze(tf_opreation4_2))
# ========== EXAMPLE 4 - Dilation Factor 4 ===========





# -- end code --


====== Dilated Kernel 3 ======
Kernal For "Familiar" Convolution for Numpy: 
 [[1 0 0 0 2 0 0 0 3]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [4 0 0 0 5 0 0 0 6]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [7 0 0 0 8 0 0 0 9]]
========== Numpy 'familiar' Convolution Results ===============
Numpy Results Shape:  (2, 2)
[[5. 5.]
 [5. 5.]]
========== Tensorfow Conv2D Results ===============
Tensorfow Conv2D Results Shape:  (1, 2, 2, 1)
[[5. 5.]
 [5. 5.]]
========== Tensorfow Atrous Conv2D Results ===============
Tensorfow Atrous Results Shape:  (1, 2, 2, 1)
[[5. 5.]
 [5. 5.]]
